### PR TITLE
Add `cli` cargo feature for CLI specific deps

### LINKED ISSUE #1: Use Cargo features for CLI deps.
Hello! Awesome work on this project! Stoked to start using it. 

With the way the dependencies are currently structured, the CLI deps will still be pulled in and compiled by even when this crate is only being used in library form. 

To mitigate this, and to preserve current install behavior, I would recommend adding a default `cli` feature. Then set the 3 CLI specific deps to `optional=true` and declare them as being part of the `cli` feature.

That should help to cut down on the number of deps for folks using this as a library. To be sure, folks will have to set their dependency on this lib to `--no-default-features` To reap those benefits.

### PR DESCRIPTION
**Pull request by thedodd**
Working as needed. Only pulls down the 3 expected deps.

Screen Shot 2020-03-29 at 12 50 16 AM

Closes #1

### CODE REVIEW

**Comment by thedodd** [comment]
@apyrgio this should do the trick.

**Comment by apyrgio** [comment]
Yep, that looks good. Before merging this, please take a look at my [`feature-cargo-deps`] branch, where I've made the following changes:

1. Moved the paragraph about dependencies in `README.md` to a separate section, next to the installation instructions.
2. Wrapped it to 80 chars and moved the dependency line in a `toml` code block.
3. Mentioned the rust-lang/cargo#1982 issue in the `Cargo.toml`, so that it's easier to revisit.
4. Added `Closes #1` to the commit message as well, so it stays in the Git history.

If you're OK with these changes, you can incorporate them to your branch with `git reset --hard <origin>/feature-cargo-deps`. Then, I will merge this pull request, cut a 0.2.1 release and publish it in `crates.io`.

[`feature-cargo-deps`]: https://github.com/apyrgio/tindercrypt/tree/feature-cargo-deps

**Comment by thedodd** [comment]
@apyrgio it's all good. Thanks for basing your branch off of my changes though `:)`, looks like it is preserving my contribution (woot woot!). Because it appears to be in tact, feel free to just merge your branch and then close this one. I'm fine with that.

**Comment by apyrgio** [comment]
Credit where credit's due ;-). I've merged the branch to `master` so I'm closing this PR. I'll proceed with the 0.2.1 release shortly.

**Pull request closed without merging**
